x-constants:
  # example of anchors (initialized with &nome valore)
  port: &app_port 8080
  db_user: &db_user app_user
  db_password: &db_password app_password
  db_name: &db_name app_database
  root_password: &root_password root_password

services:
  web:
    container_name: my-application
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "9000:8080"
    volumes:
      - .:/usr/src/app
    environment:
      # anchor usata (*nome)
      PORT: *app_port
    command: node my-node-app/app.js

  db:
    # uso di anchors per i valori delle variabili d'ambiente del db (richiesto dalla traccia)
    image: mysql:8
    container_name: my-database
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: *root_password
      MYSQL_DATABASE: *db_name
      MYSQL_USER: *db_user
      MYSQL_PASSWORD: *db_password